### ISSUE TITLE
about gogui

### ISSUE THREAD

**Issue by FengliLin** [aniljava/darkforest-variations#1]
Hello, may I ask how to run darkforest on gogui? Hoping for a detailed guideline~

**Comment by aniljava** [comment]
Assuming you were able to install [darkforestGo](https://github.com/facebookresearch/darkforestGo) successfully. 

Under Program menu of gogui, select `New Program`

for `folder` paste the full path of the folder where you installed darkforestGo
for `command` paste following :  `th cnnPlayerMCTSV2.lua --num_gpu 1 --time_limit 0

Make sure you have the neural network service already running as explained in installation instruction at  https://github.com/facebookresearch/darkforestGo the section containing `sh cnn_evaluator.sh 4 /data/local/go`

If the gogui says program did not respond or invalid, you might want to issue `killall luajit` to clear out old process.

**Comment by FengliLin** [comment]
Thx a lot! I have been confused by gogui not responding for these days. Now it can run smoothly.
